---
pipeline:
  prep:
    image: library/debian:unstable
    commands:
      - apt-get update
      - apt-get -y install devscripts git-buildpackage
      - mk-build-deps --install -t'apt-get -y'
      - mkdir build
      - cd build
      - cmake ..
      - make
      - make test
---
kind: signature
hmac: a444bb62b69e2c9321411af39897333de619f1b5a1fa93c821ee8000573f65da

...
