pipeline:
  prep:
    image: library/debian:unstable
    commands:
      - apt-get update
      - apt-get -y install devscripts git-buildpackage libnl-3-dev
      - mk-build-deps --install -t'apt-get -y'
      - mkdir build
      - cd build
      - cmake ..
      - make
      - ./netstack-tester
